language: node_js
node_js:
  - node

script:
  - yarn lint
  - yarn test
  - yarn build

deploy:
  provider: pages
  cleanup: false
  local_dir: "build"
  token: $github_token  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master